#!/usr/bin/env python3
"""GIFs and stills for the README: the whole pipeline on short 480p clips with an open licence (docs/media/README.md).

    python scripts/readme_media.py                 # everything: fetch sources, cut, process, render, encode GIFs
    python scripts/readme_media.py --only willie   # one clip
    python scripts/readme_media.py --stage gif     # re-encode the GIFs from the frames already on disk
    python scripts/readme_media.py --media-dir docs/media --out <work dir>

Per clip: <work>/<clip>/in_480p.mp4 (the 480p input), after.mp4 (dlssvid process: depth -> flow -> DLSS SR x2 -> NR -> FG x2),
after_passes/, frame dumps, and the GIF/PNG files copied into --media-dir (docs/media/ by default). Needs the dlssvid CLI
(build/release/bin or DLSSVID_CLI), ffmpeg/ffprobe on PATH, Pillow + numpy (the models/export venv has them) and an
NVIDIA RTX GPU with the DLSS DLLs in bin/nvidia (README: NVIDIA runtimes). The work dir defaults to the workspace's
Output/results/readme-media when the project lives in <workspace>/Project/, else build/release/readme-media.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import time
import urllib.request
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
CACHE = ROOT / "tests" / "data" / "cache"
UA = "VideoDLSS-readme-media/0.1 (dlss-video project; contact via GitHub)"

# 480p transcodes of the originals on Wikimedia Commons (the file pages list the licence and the authors). A transcode may be
# regenerated by Commons, so its sha256 is recorded for information and only warned about.
COMMONS = "https://upload.wikimedia.org/wikipedia/commons/transcoded"
SOURCES = {
    "willie": dict(
        title="Steamboat Willie (1928)", authors="Walt Disney, Ub Iwerks", license="Public domain",
        page="https://commons.wikimedia.org/wiki/File:Steamboat_Willie_(1928)_by_Walt_Disney.webm",
        url=f"{COMMONS}/5/5f/Steamboat_Willie_%281928%29_by_Walt_Disney.webm/Steamboat_Willie_%281928%29_by_Walt_Disney.webm.480p.vp9.webm",
        file="steamboat_willie_1928_480p.webm", sha256="", start=27.5, seconds=4.0, crop=(300, 230, 200, 150), colors=64,
        caption="meme / cartoon, 1928, 576x480",
    ),
    "popeye": dict(
        title="Popeye the Sailor Meets Sindbad the Sailor (1936)", authors="Fleischer Studios", license="Public domain",
        page="https://commons.wikimedia.org/wiki/File:Popeye_the_Sailor_Meets_Sindbad_the_Sailor_HD.webm",
        url=f"{COMMONS}/f/f5/Popeye_the_Sailor_Meets_Sindbad_the_Sailor_HD.webm/Popeye_the_Sailor_Meets_Sindbad_the_Sailor_HD.webm.480p.vp9.webm",
        file="popeye_sindbad_1936_480p.webm", sha256="", start=618.0, seconds=4.0, crop=(180, 210, 200, 150), colors=128,
        caption="cartoon, 1936, 640x480",
    ),
    "chaplin": dict(
        title="The Gold Rush (1925)", authors="Charlie Chaplin", license="Public domain",
        page="https://commons.wikimedia.org/wiki/File:The_Gold_Rush.webm",
        url=f"{COMMONS}/d/d4/The_Gold_Rush.webm/The_Gold_Rush.webm.480p.vp9.webm",
        file="the_gold_rush_1925_480p.webm", sha256="", start=3412.0, seconds=4.0, crop=(400, 260, 200, 150), colors=48,
        caption="meme / live action, 1925, 640x480 (the dance of the bread rolls)",
    ),
    "stk": dict(
        title="SuperTuxKart, a Grand Prix (gameplay recording)", authors="SuperTuxKart team; recording by the Commons uploader",
        license="CC BY 3.0",
        page="https://commons.wikimedia.org/wiki/File:SuperTuxKart_2.x_GP_with_24%25_handicap_and_road_tracks_(open_source_Mario_Kart-like_Linux_game).webm",
        url=f"{COMMONS}/0/03/SuperTuxKart_2.x_GP_with_24%25_handicap_and_road_tracks_%28open_source_Mario_Kart-like_Linux_game%29.webm/"
            "SuperTuxKart_2.x_GP_with_24%25_handicap_and_road_tracks_%28open_source_Mario_Kart-like_Linux_game%29.webm.480p.vp9.webm",
        file="supertuxkart_gp_480p.webm", sha256="", start=600.0, seconds=4.0, fps=30, crop=(430, 215, 240, 135),
        caption="game, 854x480",
    ),
}

GIF_FPS = 10
GIF_SECONDS = 2.8
GIF_COLORS = 192  # per clip: `colors` in SOURCES (black-and-white film needs far fewer)
GRID_WIDTH = 720
SCALE = 2


# ----------------------------------------------------------------------------------------------------------------- helpers
def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def run(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    r = subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8", errors="replace", **kw)
    if r.returncode != 0:
        raise RuntimeError(f"{cmd[0]} failed ({r.returncode}):\n{(r.stdout + r.stderr)[-2000:]}")
    return r


def find_cli() -> Path:
    env = os.environ.get("DLSSVID_CLI")
    if env and Path(env).exists():
        return Path(env)
    for c in [ROOT / "build" / "release" / "bin" / "dlssvid.exe", ROOT / "build" / "release" / "bin" / "dlssvid"]:
        if c.exists():
            return c
    sys.exit("dlssvid CLI not found: build the project or set DLSSVID_CLI")


def default_work() -> Path:
    ws = ROOT.parent.parent
    if ROOT.parent.name == "Project" and (ws / "Output").exists():
        return ws / "Output" / "results" / "readme-media"
    return ROOT / "build" / "release" / "readme-media"


def font(size: int) -> ImageFont.ImageFont:
    for name in ["segoeui.ttf", "arial.ttf", "DejaVuSans.ttf"]:
        try:
            return ImageFont.truetype(name, size)
        except OSError:
            continue
    return ImageFont.load_default()


def label_bar(width: int, labels: list[str], height: int = 22) -> Image.Image:
    bar = Image.new("RGB", (width, height), (24, 24, 24))
    d = ImageDraw.Draw(bar)
    f = font(14)
    cell = width // len(labels)
    for i, text in enumerate(labels):
        tw = d.textlength(text, font=f)
        d.text((i * cell + (cell - tw) / 2, 4), text, fill=(235, 235, 235), font=f)
    return bar


def to_u8(a: np.ndarray) -> np.ndarray:
    return np.clip(a.astype(np.float32) * 255.0 + 0.5, 0, 255).astype(np.uint8)


def load_npz(path: Path) -> np.ndarray:
    z = np.load(path)
    return z[z.files[0]]


def encode_gif(frames_dir: Path, out: Path, fps: int, colors: int = GIF_COLORS) -> None:
    run(["ffmpeg", "-y", "-loglevel", "error", "-framerate", str(fps), "-i", str(frames_dir / "%04d.png"),
         "-vf", f"split[a][b];[a]palettegen=max_colors={colors}:stats_mode=diff[p];[b][p]paletteuse=dither=bayer:bayer_scale=3:diff_mode=rectangle",
         "-loop", "0", str(out)])


def write_frames(frames: list[Image.Image], d: Path) -> None:
    shutil.rmtree(d, ignore_errors=True)
    d.mkdir(parents=True)
    for i, im in enumerate(frames):
        im.save(d / f"{i:04d}.png")


# ------------------------------------------------------------------------------------------------------------------ stages
def fetch(key: str, src: dict) -> Path:
    dst = CACHE / src["file"]
    if dst.exists():
        digest = sha256_of(dst)
        if src["sha256"] and digest != src["sha256"]:
            print(f"  {key}: sha256 {digest[:12]}… differs from the recorded {src['sha256'][:12]}… (Commons may have re-transcoded)")
        return dst
    CACHE.mkdir(parents=True, exist_ok=True)
    part = dst.with_suffix(".part")
    print(f"  {key}: downloading {src['url'].split('/')[-1][:70]}")
    for attempt in range(8):
        have = part.stat().st_size if part.exists() else 0
        req = urllib.request.Request(src["url"], headers={"User-Agent": UA, **({"Range": f"bytes={have}-"} if have else {})})
        try:
            with urllib.request.urlopen(req, timeout=120) as r, open(part, "ab" if have else "wb") as f:
                for chunk in iter(lambda: r.read(1 << 20), b""):
                    f.write(chunk)
            part.rename(dst)
            print(f"  {key}: {dst.stat().st_size / 1e6:.1f} MB, sha256 {sha256_of(dst)}")
            return dst
        except Exception as e:  # noqa: BLE001 — retried with a pause (Commons rate-limits bursts with HTTP 429)
            print(f"  {key}: {str(e)[:80]} — retry {attempt + 1}")
            time.sleep(60 if "429" in str(e) else 15)
    raise RuntimeError(f"{key}: download failed")


def cut(src_file: Path, src: dict, d: Path) -> Path:
    out = d / "in_480p.mp4"
    if out.exists():
        return out
    d.mkdir(parents=True, exist_ok=True)
    run(["ffmpeg", "-y", "-loglevel", "error", "-ss", str(src["start"]), "-i", str(src_file), "-t", str(src["seconds"]),
         "-vf", "scale=trunc(iw/2)*2:trunc(ih/2)*2", "-r", str(src.get("fps", 24)), "-c:v", "libx264", "-preset", "slow", "-crf", "12", "-pix_fmt", "yuv420p",
         "-an", str(out)])
    return out


def probe(video: Path) -> tuple[int, int, float, int]:
    r = run(["ffprobe", "-v", "error", "-select_streams", "v:0", "-count_frames", "-show_entries",
             "stream=width,height,r_frame_rate,nb_read_frames", "-of", "json", str(video)])
    s = json.loads(r.stdout)["streams"][0]
    num, den = s["r_frame_rate"].split("/")
    return int(s["width"]), int(s["height"]), int(num) / int(den), int(s["nb_read_frames"])


def process(cli: Path, inp: Path, d: Path) -> Path:
    out = d / "after.mp4"
    if out.exists() and (d / "process.json").exists():
        return out
    run([str(cli), "process", "-i", str(inp), "-o", str(out), "--scale", str(SCALE), "--codec", "h264_nvenc", "--codec-opt", "b=20M",
         "--json", str(d / "process.json")])
    return out


def export_pass(cli: Path, d: Path, name: str) -> Path:
    out = d / f"{name}_npz"
    if out.exists() and any(out.glob("*.npz")):
        return out
    run([str(cli), "export", "--from-dir", str(d / "after_passes" / name), "-o", str(out), "--format", "npz"])
    return out


def source_frames(inp: Path, d: Path) -> Path:
    out = d / "src_png"
    if out.exists() and any(out.glob("*.png")):
        return out
    out.mkdir()
    run(["ffmpeg", "-y", "-loglevel", "error", "-i", str(inp), str(out / "%06d.png")])
    return out


def render(cli: Path, inp: Path, d: Path, frame: int, source: str, display: str | None, out: Path, mode: str = "single",
           sources: str | None = None, size: tuple[int, int] | None = None) -> None:
    if out.exists():
        return
    cmd = [str(cli), "render", "-i", str(inp), "--passes", str(d / "after_passes"), "--frame", str(frame), "--mode", mode, "-o", str(out)]
    if size:
        cmd += ["--size", f"{size[0]}x{size[1]}"]  # arrows are drawn for the output size, so they stay legible in a half-size panel
    if mode == "single":
        cmd += ["--source", source]
        if display:
            cmd += ["--display", display]
    else:
        cmd += ["--sources", sources]
    run(cmd)


def gif_frames_idx(n_src: int, fps: float) -> list[int]:
    step = max(1, int(round(fps / GIF_FPS)))
    n = min(n_src, int(GIF_SECONDS * fps))
    return list(range(0, n, step))


def gif_fps(fps: float) -> int:
    return int(round(fps / max(1, int(round(fps / GIF_FPS)))))


def crop_box(src: dict, w: int, h: int, scale: int) -> tuple[int, int, int, int]:
    cx, cy, cw, ch = src["crop"]
    x0 = max(0, min(w - cw, cx - cw // 2)) * scale
    y0 = max(0, min(h - ch, cy - ch // 2)) * scale
    return x0, y0, cw * scale, ch * scale


def before_after(key: str, src: dict, d: Path, media: Path, w: int, h: int, fps: float, n_src: int) -> None:
    """Side by side at 1:1 of the result: the 480p input scaled x2 with bicubic (what a player would show) vs DLSS SR x2 + NR."""
    x0, y0, cw, ch = crop_box(src, w, h, SCALE)
    frames = []
    for k in gif_frames_idx(n_src, fps):
        before = Image.open(d / "src_png" / f"{k + 1:06d}.png").convert("RGB")
        before = before.resize((w * SCALE, h * SCALE), Image.BICUBIC).crop((x0, y0, x0 + cw, y0 + ch))
        after = Image.fromarray(to_u8(load_npz(d / "color_nr_npz" / f"color_nr_{k:06d}.npz"))).crop((x0, y0, x0 + cw, y0 + ch))
        pair = Image.new("RGB", (cw * 2 + 2, ch + 22), (24, 24, 24))
        pair.paste(label_bar(cw * 2 + 2, ["480p input, bicubic x2", f"DLSS SR x{SCALE} + Neural Rendering"]), (0, 0))
        pair.paste(before, (0, 22))
        pair.paste(after, (cw + 2, 22))
        frames.append(pair)
    write_frames(frames, d / "gif_before_after")
    encode_gif(d / "gif_before_after", media / f"{key}_before_after.gif", gif_fps(fps), src.get("colors", GIF_COLORS))
    frames[len(frames) // 2].save(media / f"{key}_before_after.png", optimize=True)


def pass_media(key: str, src: dict, d: Path, media: Path, cli: Path, inp: Path, w: int, h: int, fps: float, n_src: int, mv_display: str) -> None:
    """The passes of one clip: 2x2 grid (source | depth | motion vectors | result), depth, motion vectors and FG."""
    idx = gif_frames_idx(n_src, fps)
    for k in idx:
        render(cli, inp, d, k, "source", None, d / "render" / f"grid-mvraw_{k:04d}.png", mode="grid", sources="source,depth_dlss,mv_raw,color_nr")
        render(cli, inp, d, k, "depth_dlss", "viridis", d / "render" / f"depth_{k:04d}.png")
        render(cli, inp, d, k, "mv_dlss", mv_display, d / "render" / f"mv-{mv_display}-half_{k:04d}.png", size=(w // 2, h // 2))
    # grid: as the viewport shows it, at the source resolution
    grid0 = Image.open(d / "render" / f"grid-mvraw_{idx[0]:04d}.png")
    gw = min(GRID_WIDTH, grid0.width)
    gh = round(grid0.height * gw / grid0.width)
    frames = []
    for k in idx:
        g = Image.open(d / "render" / f"grid-mvraw_{k:04d}.png").convert("RGB").resize((gw, gh), Image.LANCZOS)
        im = Image.new("RGB", (gw, gh + 22), (24, 24, 24))
        im.paste(label_bar(gw, ["source 480p", "depth_dlss (viridis)", "mv_raw (HSV)", "DLSS SR x2 + NR"]), (0, 0))
        im.paste(g, (0, 22))
        frames.append(im)
    write_frames(frames, d / "gif_grid")
    encode_gif(d / "gif_grid", media / f"{key}_passes_grid.gif", gif_fps(fps))
    # depth and motion vectors next to the source, half size
    for name, file_stem, disp_label in [("depth", "depth", "depth_dlss, viridis"), ("mv", f"mv-{mv_display}-half", f"mv_dlss, {mv_display}")]:
        frames = []
        for k in idx:
            s = Image.open(d / "src_png" / f"{k + 1:06d}.png").convert("RGB")
            p = Image.open(d / "render" / f"{file_stem}_{k:04d}.png").convert("RGB")
            s = s.resize((w // 2, h // 2), Image.LANCZOS)
            if p.size != (w // 2, h // 2):
                p = p.resize((w // 2, h // 2), Image.LANCZOS)
            im = Image.new("RGB", (w + 2, h // 2 + 22), (24, 24, 24))
            im.paste(label_bar(w + 2, ["source", disp_label]), (0, 0))
            im.paste(s, (0, 22))
            im.paste(p, (w // 2 + 2, 22))
            frames.append(im)
        write_frames(frames, d / f"gif_{name}")
        encode_gif(d / f"gif_{name}", media / f"{key}_{name}.gif", gif_fps(fps))
    fg_media(key, src, d, media, w, h, idx)


def nr_media(key: str, src: dict, d: Path, media: Path, w: int, h: int, fps: float, n_src: int) -> None:
    """NR: the same crop before (color_sr) and after (color_nr) the neural rendering stage."""
    idx = gif_frames_idx(n_src, fps)
    x0, y0, cw, ch = crop_box(src, w, h, SCALE)
    frames = []
    for k in idx:
        a = Image.fromarray(to_u8(load_npz(d / "color_sr_npz" / f"color_sr_{k:06d}.npz"))).crop((x0, y0, x0 + cw, y0 + ch))
        b = Image.fromarray(to_u8(load_npz(d / "color_nr_npz" / f"color_nr_{k:06d}.npz"))).crop((x0, y0, x0 + cw, y0 + ch))
        im = Image.new("RGB", (cw * 2 + 2, ch + 22), (24, 24, 24))
        im.paste(label_bar(cw * 2 + 2, ["after DLSS SR x2 (color_sr)", "after Neural Rendering (color_nr)"]), (0, 0))
        im.paste(a, (0, 22))
        im.paste(b, (cw + 2, 22))
        frames.append(im)
    write_frames(frames, d / "gif_nr")
    encode_gif(d / "gif_nr", media / f"{key}_nr.gif", gif_fps(fps), src.get("colors", GIF_COLORS))


def fg_media(key: str, src: dict, d: Path, media: Path, w: int, h: int, idx: list[int]) -> None:
    """FG: slow motion over consecutive color_fg frames — every other one is generated."""
    x0, y0, cw, ch = crop_box(src, w, h, SCALE)
    fg_files = sorted((d / "color_fg_npz").glob("*.npz"))
    first = 2 * idx[len(idx) // 3]
    frames = []
    for j in range(first, min(first + 24, len(fg_files))):
        im_full = Image.fromarray(to_u8(load_npz(fg_files[j]))).crop((x0, y0, x0 + cw, y0 + ch))
        im = Image.new("RGB", (cw, ch + 22), (24, 24, 24))
        gen = j % 2 == 1
        im.paste(label_bar(cw, [f"frame {j}: {'generated by DLSS FG' if gen else 'source frame'}  (1/4 speed)"]), (0, 0))
        im.paste(im_full, (0, 22))
        if gen:
            ImageDraw.Draw(im).rectangle((0, 22, cw - 1, ch + 21), outline=(255, 170, 40), width=3)
        frames.append(im)
    write_frames(frames, d / "gif_fg")
    encode_gif(d / "gif_fg", media / f"{key}_fg.gif", 6)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--only", nargs="*", default=None, help="clip keys (default: all)")
    ap.add_argument("--stage", choices=["all", "fetch", "cut", "process", "frames", "gif"], default="all")
    ap.add_argument("--out", type=Path, default=default_work())
    ap.add_argument("--media-dir", type=Path, default=ROOT / "docs" / "media")
    ap.add_argument("--passes-for", default="stk", help="clip whose passes get the grid / depth / mv / fg GIFs")
    ap.add_argument("--nr-for", default="chaplin", help="clip for the NR GIF (film grain and skin show the stage best)")
    ap.add_argument("--mv-display", default="mv_arrows", choices=["mv_hsv", "mv_arrows", "mv_magnitude"])
    args = ap.parse_args()
    cli = find_cli()
    keys = args.only or list(SOURCES)
    args.out.mkdir(parents=True, exist_ok=True)
    args.media_dir.mkdir(parents=True, exist_ok=True)
    report = {}
    for key in keys:
        src = SOURCES[key]
        d = args.out / key
        print(f"[{key}] {src['title']}")
        src_file = fetch(key, src)
        if args.stage == "fetch":
            continue
        inp = cut(src_file, src, d)
        w, h, fps, n_src = probe(inp)
        print(f"  input {w}x{h} @ {fps:g} fps, {n_src} frames")
        if args.stage == "cut":
            continue
        if args.stage in ("all", "process"):
            t0 = time.time()
            process(cli, inp, d)
            print(f"  processed in {time.time() - t0:.0f} s")
            if args.stage == "process":
                continue
        if args.stage in ("all", "frames", "gif"):
            source_frames(inp, d)
            for name in ["color_sr", "color_nr"] + (["color_fg"] if key == args.passes_for else []):
                export_pass(cli, d, name)
            if args.stage == "frames":
                continue
        before_after(key, src, d, args.media_dir, w, h, fps, n_src)
        if key == args.passes_for:
            pass_media(key, src, d, args.media_dir, cli, inp, w, h, fps, n_src, args.mv_display)
        if key == args.nr_for:
            nr_media(key, src, d, args.media_dir, w, h, fps, n_src)
        rep = json.loads((d / "process.json").read_text(encoding="utf-8")) if (d / "process.json").exists() else {}
        report[key] = {"input": f"{w}x{h} @ {fps:g} fps, {n_src} frames", "seconds": rep.get("seconds"),
                       "stages": {s.get("stage"): round(s.get("ms_per_frame", 0)) for s in rep.get("stages", [])}}
        sizes = {p.name: round(p.stat().st_size / 1e6, 2) for p in sorted(args.media_dir.glob(f"{key}_*"))}
        print("  media:", sizes)
    (args.out / "summary.json").write_text(json.dumps({"sources": SOURCES, "clips": report}, indent=1, ensure_ascii=False), encoding="utf-8")
    total = sum(p.stat().st_size for p in args.media_dir.glob("*.gif")) / 1e6
    print(f"GIF total in {args.media_dir}: {total:.1f} MB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
